//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyCompany("VersionOne, Inc")]
[assembly: AssemblyCopyright("Copyright 2008-2013, VersionOne, Inc. Licensed under modified BSD.")]
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.0.1")]
[assembly: AssemblyInformationalVersion("See https://github.com/versionone/VersionOne.ServiceHost.Core/wiki")]
[assembly: AssemblyConfiguration("Release")]
[assembly: AssemblyProduct("VersionOne.ServiceHost.Core")]
[assembly: AssemblyTitle("VersionOne ServiceHost Core")]
[assembly: AssemblyDescription("VersionOne ServiceHost Core Release Build")]


