// Auto generated by build.sh at Thu Jan 23 19:01:20 UTC 2014

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyVersion("1.0.1341")]
[assembly: AssemblyFileVersion("1.0.1341")]
[assembly: AssemblyInformationalVersion("See https://github.com/versionone/VersionOne.ServiceHost.Core/wiki")]

[assembly: AssemblyProduct("VersionOne.ServiceHost.Core")]
[assembly: AssemblyTitle("VersionOne.ServiceHost.Core")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyCompany("VersionOne, Inc.")]
[assembly: AssemblyCopyright("Copyright 2008-2014, VersionOne, Inc. Licensed under modified BSD.")]

[assembly: AssemblyConfiguration("Release")]
[assembly: ComVisibleAttribute(false)]
