// This file will be generated by build.sh. No need to commit changes.

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyVersion("0.0.0.0")]
[assembly: AssemblyFileVersion("0.0.0.0")]
[assembly: AssemblyInformationalVersion("See https://github.com/versionone/VersionOne.ServiceHost.Core/wiki")]

[assembly: AssemblyProduct("VersionOne.ServiceHost.Core")]
[assembly: AssemblyTitle("VersionOne.ServiceHost.Core")]
[assembly: AssemblyDescription("VersionOne ServiceHost Core VersionOne.ServiceHost.Core Release Build")]
[assembly: AssemblyCompany("VersionOne, Inc.")]
[assembly: AssemblyCopyright("Copyright 2008-2013, VersionOne, Inc., Licensed under modified BSD.")]

[assembly: AssemblyConfiguration("Release")]
